version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp
      POSTGRES_DB: mcp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  registry:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://mcp:mcp@db:5432/mcp?sslmode=disable
    depends_on:
      - db
volumes:
  db_data: